routes/routeempresa.py
from flask import render_template, url_for, redirect, flash, request
from flask import Blueprint
from flask_sqlalchemy import SQLAlchemy
from flask_paginate import Pagination
from classes.empresa import Empresa
from classes.enderecoempresa import EnderecoEmpresa
import classes.cnae
from app import db

#-------------------------------------------------------------------------------
#----------------------------- ROTAS DA EMPRESA --------------------------------
#-------------------------------------------------------------------------------

# Utilização de BLUEPRINT (ver em: https://flask.palletsprojects.com/en/1.1.x/blueprints/#blueprints)
empresa_page = Blueprint('empresa_page', __name__, template_folder='routes')

# Rota para carregar as informações digitadas ao se cadastrar uma nova EMPRESA
@empresa_page.route("/cadastro", methods=['GET', 'POST'])
def cadastro():
    if request.method == 'POST':
        numeropasta = request.form.get("numeropasta")
        razaosocial = request.form.get("razaosocial")
        inscest = request.form.get("inscricaoestadual")
        cnpj = request.form.get("cnpj")
        cxpostal = request.form.get("caixapostal")
        email = request.form.get("email")
        cnae_id = str(request.form.get("cnae"))
        telefone1 = request.form.get("telefone1")
        telefone2 = request.form.get("telefone2")
        logradouro = request.form.get("logradouro")
        complemento = request.form.get("complemento")
        bairro = request.form.get("bairro")
        cidade = request.form.get("cidade")
        estado = request.form.get("estado")
        cep = str(request.form.get("cep"))
        
        # Construtor da classe EMPRESA
        empresa = Empresa(numeropasta, razaosocial, inscest, cnpj, cxpostal, email, cnae_id, telefone1, telefone2)
        db.session.add(empresa)
        # O comando abaixo força a criação do ID no BD
        db.session.flush()

        # 'Captura' o ID da empresa para ser adicionado na tabela ENDERECOEMPRESA
        empresa_id = empresa.idempresa

        # Construtor da classe ENDERECOEMPRESA
        enderecoempresa = EnderecoEmpresa(logradouro, complemento, bairro, cidade, estado, cep, empresa_id=empresa.idempresa)
        db.session.add(enderecoempresa)
        db.session.commit()
        
        mensagem = "Empresa gravada com sucesso"
        alerta = "success"

        flash(mensagem, alerta)
        return redirect(url_for("empresa_page.listar"))

# Rota para a página que exibe a listagem com as EMPRESAS.
# Nessa listagem ocorre a PAGINAÇÃO das empresas.
# Ou seja, elas são exibidas de 10 em 10 empresas.
@empresa_page.route("/lista")
def listar():
    limit = 10
    empresas = Empresa.query.order_by(Empresa.numeropasta).all()
    cnae = classes.cnae.Cnae.query.all()
    enderecoempresa = EnderecoEmpresa.query.all()

    page = int(request.args.get("page", 1))
    start = (page - 1) * limit
    end = page * limit if len(empresas) > page * limit else len(empresas)
    paginate = Pagination(page=page, total=len(empresas), css_framework='bootstrap4')
    pageempresas = Empresa.query.order_by(Empresa.numeropasta).slice(start, end)
    return render_template("lista.html", empresas = pageempresas, cnae = cnae, start=start + 1, end=end,
                            enderecoempresa = enderecoempresa, pagination=paginate)

# Rota para exclusão de uma EMPRESA existente
@empresa_page.route("/excluir/<int:id>", methods = ['GET', 'POST'])
def excluir(id):
    empresa = Empresa.query.get(id)
    idenderecoempresa = empresa.idempresa
    enderecoempresa = EnderecoEmpresa.query.filter_by(empresa_id=idenderecoempresa).first()
    
    db.session.delete(enderecoempresa)
    db.session.commit()
    
    db.session.delete(empresa)
    db.session.commit()

    mensagem = "Empresa deletada"
    alerta = "success"

    flash(mensagem, alerta)
    return redirect(url_for("empresa_page.listar"))

# Rota para a página de alteração do cadastro da EMPRESA. 
# É importante que seja adicionado o método GET (juntamente com o método POST)
# em ROUTE para que traga as informações que serão alteradas
@empresa_page.route("/atualizar/<int:id>", methods=['GET','POST'])
def atualizar(id):
    cnae = classes.cnae.Cnae.query.all()
    empresa = Empresa.query.get(id)
    idenderecoempresa = empresa.idempresa
    enderecoempresa = EnderecoEmpresa.query.filter_by(empresa_id=idenderecoempresa).first()

    if (request.method == 'POST'):
        numeropasta = request.form.get("numeropasta")
        razaosocial = request.form.get("razaosocial")
        inscestadual = request.form.get("inscricaoestadual")
        cnpj = request.form.get("cnpj")
        cxpostal = request.form.get("caixapostal")
        email = request.form.get("email")
        cnae = request.form.get("cnae")
        telefone1 = request.form.get("telefone1")
        telefone2 = request.form.get("telefone2")
        cep = request.form.get("cep")
        logradouro = request.form.get("logradouro")
        complemento = request.form.get("complemento")
        bairro = request.form.get("bairro")
        estado = request.form.get("estado")
        cidade = request.form.get("cidade")

        # Aqui pode ser criada uma validação para verificar se algo foi digitado para ser gravado no BD
        # Atualizando no BD as informações da empresa
        empresa.numeropasta = numeropasta
        empresa.razaosocial = razaosocial
        empresa.inscricaoestadual = inscestadual
        empresa.cnpj = cnpj
        empresa.caixapostal = cxpostal
        empresa.email = email
        empresa.cnae_id = cnae
        empresa.telefone1 = telefone1
        empresa.telefone2 = telefone2

        # Um commit para cada tabela. Commit na tabela EMPRESA
        db.session.commit()

        # Atualizando no BD as informações do endereço da empresa
        enderecoempresa.cep = cep
        enderecoempresa.logradouro = logradouro
        enderecoempresa.complemento = complemento
        enderecoempresa.bairro = bairro
        enderecoempresa.estado = estado
        enderecoempresa.cidade = cidade

        # Commit na tabela ENDERECOEMPRESA
        db.session.commit()

        mensagem = "Empresa atualizada"
        alerta = "info"

        flash(mensagem, alerta)
        
        return redirect(url_for("empresa_page.listar"))
        # return render_template("lista.html")
    
    return render_template("atualizaempresa.html", empresa = empresa, cnae = cnae, enderecoempresa = enderecoempresa)

routes/routeindex.py
from flask import Blueprint, render_template
# Rota para a página inicial
index_page = Blueprint('index_page', __name__, template_folder='routes')
@index_page.route("/")
def index():
    return render_template("index.html")

routes/routelap.py
from flask import render_template, url_for, redirect, flash, request
from flask import Blueprint
from flask_sqlalchemy import SQLAlchemy
from flask_paginate import Pagination
from classes.produto import Produto
from classes.atividade import Atividade
from classes.licenca import Licenca
from classes.empresa import Empresa
from app import db

#-------------------------------------------------------------------------------
#-------------------- ROTAS LICENÇAS/ATIVIDADES/PRODUTOS -----------------------
#-------------------------------------------------------------------------------

# Utilização de BLUEPRINT (ver em: https://flask.palletsprojects.com/en/1.1.x/blueprints/#blueprints)
lap_page = Blueprint('lap_page', __name__, template_folder='routes')

# Como se trata de uma DUALLISTBOX, não existe as funções
# para cadastrar e excluir PRODUTOS ou ATIVIDADES

# Rota para a página de ATIVIDADES e PRODUTOS que estão vinculadas a LICENÇA
# É importante que seja adicionado o método GET (juntamente com o método POST)
# em ROUTE para que traga as informações que serão alteradas
@lap_page.route("/lap/<int:id>", methods=['GET','POST'])
def listalap(id):
    licenca = Licenca.query.get(id)
    produtos = Produto.query.all()
    atividades = Atividade.query.all()
    empresa = Empresa.query.get(licenca.empresa_id)
    
    return render_template("listalap.html", empresa = empresa, licenca = licenca,
                            produtos = produtos, atividades = atividades)

# Rota para alteração de ATIVIDADES e/ou PRODUTOS
@lap_page.route("/atualizalap/<int:id>", methods=['GET','POST'])
def atualizalap(id):
    licenca = Licenca.query.get(id)
    produtos = Produto.query.all()
    atividades = Atividade.query.all()

    if (request.method == 'POST'):
        listaatividades = []
        listaprodutos = []
        # Conversão de uma lista de string para uma lista de inteiro
        # Extraído de https://www.geeksforgeeks.org/python-converting-all-strings-in-list-to-integers/
        listaatividades = [int(i) for i in request.form.getlist("duallistbox_atividades[]")]
        listaprodutos = [int(i) for i in request.form.getlist("duallistbox_produtos[]")]
        empresa_id = request.form.get("empresaid")

        licenca.atividade_id = listaatividades
        licenca.produto_id = listaprodutos

        # Commit na tabela LICENÇA
        db.session.commit()

        mensagem = "Atividades/Produtos atualizados"
        alerta = "info"

        flash(mensagem, alerta)
        
        return redirect(url_for("licenca_page.listarlicencas", id=empresa_id))
    
    return render_template("listalap.html", licenca = licenca, produtos = produtos, atividades = atividades)

routes/routeorgao.py
from flask import render_template, url_for, redirect, flash, request
from flask import Blueprint
from flask_sqlalchemy import SQLAlchemy
from flask_paginate import Pagination
from classes.orgao import Orgao
from app import db

#-------------------------------------------------------------------------------
#----------------------------- ROTAS DA EMPRESA --------------------------------
#-------------------------------------------------------------------------------

# Utilização de BLUEPRINT (ver em: https://flask.palletsprojects.com/en/1.1.x/blueprints/#blueprints)
orgao_page = Blueprint('orgao_page', __name__, template_folder='routes')

# Rota para carregar as informações digitadas ao se cadastrar um novo ORGÃO
@orgao_page.route("/cadastroorgao", methods=['GET', 'POST'])
def cadastro():
    if request.method == 'POST':
        nomeorgao = request.form.get("nome")
        contato = request.form.get("contato")
        telefone1 = request.form.get("telefone1")
        telefone2 = request.form.get("telefone2")
        logradouro = request.form.get("logradouro")
        complemento = request.form.get("complemento")
        bairro = request.form.get("bairro")
        cidade = request.form.get("cidade")
        estado = request.form.get("estado")
        cep = str(request.form.get("cep"))
        
        # Construtor da classe ORGÃO
        orgao = Orgao(nomeorgao, contato, telefone1, telefone2, logradouro, complemento, bairro, 
                        cidade, estado, cep)
        db.session.add(orgao)
        db.session.commit()
        
        mensagem = "Orgão gravado com sucesso"
        alerta = "success"

        flash(mensagem, alerta)
        return redirect(url_for("orgao_page.listar"))

# Rota para a página que exibe a listagem de TODOS os ORGÃOS.
@orgao_page.route("/listaorgao")
def listar():
    limit = 10
    orgaos = Orgao.query.order_by(Orgao.idorgao).all()

    page = int(request.args.get("page", 1))
    start = (page - 1) * limit
    end = page * limit if len(orgaos) > page * limit else len(orgaos)
    paginate = Pagination(page=page, total=len(orgaos), css_framework='bootstrap4')
    pageOrgaos = Orgao.query.order_by(Orgao.idorgao).slice(start, end)
    return render_template("listaorgao.html", orgaos = pageOrgaos, start=start + 1, end=end, pagination=paginate)

# Rota para exclusão de um ORGÃO existente
@orgao_page.route("/excluiorgao/<int:id>", methods = ['GET', 'POST'])
def excluir(id):
    orgao = Orgao.query.get(id)
    
    db.session.delete(orgao)
    db.session.commit()

    mensagem = "Orgão deletado"
    alerta = "success"

    flash(mensagem, alerta)
    return redirect(url_for("orgao_page.listar"))

# Rota para a página de alteração das informações do Órgão. 
# É importante que seja adicionado o método GET (juntamente com o método POST)
# em ROUTE para que traga as informações que serão alteradas
@orgao_page.route("/atualizarorgao/<int:id>", methods=['GET','POST'])
def atualizar(id):
    orgao = Orgao.query.get(id)
    
    if (request.method == 'POST'):
        nomeorgao = request.form.get("nome")
        contato = request.form.get("contato")
        telefone1 = request.form.get("telefone1")
        telefone2 = request.form.get("telefone2")
        logradouro = request.form.get("logradouro")
        complemento = request.form.get("complemento")
        bairro = request.form.get("bairro")
        cidade = request.form.get("cidade")
        estado = request.form.get("estado")
        cep = str(request.form.get("cep"))

        # Aqui pode ser criada uma validação para verificar se algo foi digitado para ser gravado no BD
        # Atualizando no BD as informações da empresa
        orgao.nomeorgao = nomeorgao
        orgao.contato = contato
        orgao.telefone1 = telefone1
        orgao.telefone2 = telefone2
        orgao.logradouro = logradouro
        orgao.complemento = complemento
        orgao.bairro = bairro
        orgao.cidade = cidade
        orgao.estado = estado
        orgao.cep = cep

        db.session.commit()

        mensagem = "Órgão atualizado"
        alerta = "info"

        flash(mensagem, alerta)
        
        return redirect(url_for("orgao_page.listar"))
    
    return render_template("atualizaorgao.html", orgao = orgao)

templates/lista.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Não utilizar o JQUERY SLIM pois com ele não funciona o autocompletamento do endereço -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js" 
        integrity="sha512-0XDfGxFliYJPFrideYOoxdgNIvrwGTLnmK20xZbCAvPfLGQMzHUsaqZK8ZoH+luXGRxTrS46+Aq400nCnAT0/w=="
        crossorigin="anonymous"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>    
    <script src="/static/js/mask.js"></script>
    <script src="/static/js/pesquisa.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/paginacao.css">

    <title>Solid Consulting - Empresas</title>
</head>

<body>
    <div class="inner">
        <!-- Note: Internet Explorer 10 and earlier versions do not support the justify-content property. -->
        <nav class="navbar navbar-expand-sm justify-content-between">
            <h1><p class="text-center">Empresas</p></h1>
            <a class="navbar-brand" href="{{ url_for('index_page.index') }}">
                <img src="/static/images/solid_icon.png" alt="" width="120" height="70">
            </a>
        </nav> 
    </div>
    <div class="inner">
        <!-- <div class="row"> -->
            <div class="col md-12">
                <div class="jumbotron p-3">
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">
                                        <img src="/static/images/search.png" width="20" height="20">
                                    </span>
                                </div>
                                <input class="form-control" id="myInput" type="text" placeholder="Pesquisa..">
                            </div>
                        </div>
                        <div class="form-group col-md-9">
                            <button type="button" class="btn btn-success mb-3 float-right" data-toggle="modal"
                                data-target="#mymodal">Nova Empresa</button>
                        </div>
                    </div>
                        {% for category, message in get_flashed_messages(with_categories=true) %}
                        <div class="alert alert-{{ category }} alert-dismissable" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">x</span>
                            </button>
                            {{message}}
                        </div>
                        {% endfor %}
                
                    <table class="table table-sm table-hover table-dark datatable" id="tabela">
                        <thead>
                            <tr>
                                <th width="30">Pasta Número</th>
                                <th class="text-center" width="320">Razão Social</th>
                                <th class="text-center" width="100">Inscrição Estadual</th>
                                <th class="text-center" width="100">CNPJ</th>
                                <th class="text-center" width="300">Email</th>
                                <th width="350">CNAE</th>
                            </tr>
                        </thead>
                        
                        {% for empresa in empresas %}
                        <tbody id="myTable">
                            <tr>
                                <td>{{ empresa.numeropasta }}</td>
                                <td align="center">{{ empresa.razaosocial }}</td>
                                <td align="center">{{ empresa.inscricaoestadual }}</td>
                                <td align="center">{{ empresa.cnpj }}</td>
                                <td align="center">{{ empresa.email }}</td>
                                {% for c in cnae %}
                                    {% if c.idcnae == empresa.cnae_id %}
                                        <td>{{ c.descricao }}</td>
                                        {{ break }}
                                    {% endif %}
                                {% endfor %}
                                <td>
                                    <a href="{{ url_for('empresa_page.atualizar', id=empresa.idempresa) }}" class="btn btn-outline-warning btn-xs" title="Editar">
                                        <img src="{{ url_for('static', filename='images/edit2.png') }}" width="30" height="28">
                                    </a>
                                    <a href="{{ url_for('licenca_page.listarlicencas', id=empresa.idempresa) }}" class="btn btn-outline-info btn-xs" title="Licenças">
                                        <img src="{{ url_for('static', filename='images/diploma1.png') }}" width="30" height="28">
                                    </a>
                                    <a href="{{ url_for('empresa_page.excluir', id=empresa.idempresa) }}" class="btn btn-outline-danger btn-xs" title="Excluir"
                                    onclick="return confirm('Deseja realmente excluir {{ empresa.razaosocial }}?')">
                                        <img src="{{ url_for('static', filename='images/delete5.png') }}" width="30" height="28">
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                        {% endfor %}
                    </table>  
                </div>

                <!-- Modal Adicionar Empresa-->
                <div id="mymodal" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Nova Empresa</h4>
                            </div>
                            <div class="modal-body">
                                <form action="{{url_for('empresa_page.cadastro')}}" method="POST">
                                    <div class="form-row">
                                        <div class="form-group col-sm-4">
                                            <label>Número da Pasta</label>
                                            <input type="text" class="form-control" name="numeropasta"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Razão Social</label>
                                        <input type="text" class="form-control" name="razaosocial"/>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Inscrição Estadual</label>
                                            <input type="text" class="form-control" name="inscricaoestadual" placeholder="Somente números"/>
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>CNPJ</label>
                                            <input type="text" class="form-control" name="cnpj" 
                                                placeholder="Somente números" minlength="14" maxlength="14"/>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Caixa Postal</label>
                                            <input type="text" class="form-control" name="caixapostal"/>
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Email</label>
                                            <input type="text" class="form-control" name="email"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="formControlCnae">CNAE</label>
                                        <select class="form-control" name="cnae" id="formControlCnae">
                                            <option>-- Selecione uma opção --</option>
                                            {% for c in cnae %}
                                            <option value="{{ c.idcnae }}">{{ c.codigo }} - {{ c.descricao }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label>Telefone Principal</label>
                                            <input type="text" class="form-control" id="telefone3" name="telefone1" placeholder="(XX) XXXXX-XXXX"/>
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Outro Telefone</label>
                                            <input type="text" class="form-control" id="telefone4" name="telefone2" placeholder="(XX) XXXXX-XXXX"/>
                                        </div>
                                    </div>
                                    <hr/>
                                    <div class="form-group">
                                        <label>CEP</label>
                                        <input type="text" class="form-control" id="cep" name="cep"/>
                                    </div>
                                    <div class="form-group">
                                        <label>Logradouro</label>
                                        <input type="text" class="form-control" id="logradouro" name="logradouro"/>
                                    </div>
                                    <div class="form-group">
                                        <label>Complemento</label>
                                        <input type="text" class="form-control" id="complemento" name="complemento"/>
                                    </div>
                                    <div class="form-group">
                                        <label>Bairro</label>
                                        <input type="text" class="form-control" id="bairro" name="bairro"/>
                                    </div>
                                    <div class="form-group">
                                        <label>Estado</label>
                                        <input type="text" class="form-control" id="cidade" name="cidade"/>
                                    </div>
                                    <div class="form-group">
                                        <label>Estado</label>
                                        <input type="text" class="form-control" id="uf" name="estado"/>
                                    </div>
                                    
                                    <script src="/static/js/preenche_endereco.js"></script>
                                    <hr>
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Adicionar</button>
                                        <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Cancelar</button>
                                    </div>
                                </form>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        <!-- </div> -->
    </div>
    <div class="form-row align-itens-center ml-3">
        <div class="col-md-6">
            {% if pagination.total == 0 %}
            <h3>Nenhuma empresa cadastrada</h3>
            {% else %}
            <h3>Exibindo de {{ start }} a {{ end }} Empresas. Total {{ pagination.total }} Empresas</h3>
            {% endif %}
        </div>
        <div class="col-md-4">
            {{ pagination.links }}
        </div>
        <div class="col-md-2">
            <a href="{{ url_for('index_page.index') }}" class="btn btn-primary">Voltar</a>
        </div>    
    </div>
</body>
</html>

templates/listalap.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/bootstrap-duallistbox.css">
    <!-- Não utilizar o JQUERY SLIM pois com ele não funciona o autocompletamento do endereço -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js" 
        integrity="sha512-0XDfGxFliYJPFrideYOoxdgNIvrwGTLnmK20xZbCAvPfLGQMzHUsaqZK8ZoH+luXGRxTrS46+Aq400nCnAT0/w=="
        crossorigin="anonymous"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/mask.js"></script>
    <script src="/static/js/jquery.bootstrap-duallistbox.js"></script>
    
    <title>Solid Consulting - Atividades/Produtos</title>
</head>

<body>
    <div>
        <nav class="navbar justify-content-between">
            <a class="navbar-brand" href="{{ url_for('index_page.index') }}">
                <img src="/static/images/solid_icon.png" alt="" width="120" height="70">
            </a>
            <h1><p class="text-center">{{ empresa.razaosocial }}</p></h1>
        </nav>         
    </div>
    <div>
        <h1><p class="text-center">Atividades</p></h1>      
    </div>
    <div class="col md-6">
        <!-- Messagem para cada ação (alterar ou excluir) executada. -->
        {% for category, message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ category }} alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span aria-hidden="true">x</span>
            </button>
            {{message}}
        </div>
        {% endfor %}
        <form id="lapform" action="{{url_for('lap_page.atualizalap', id=licenca.idlicenca)}}" method="POST">
            <input type="hidden" name="empresaid" value="{{empresa.idempresa}}">
            <select multiple="multiple" size="7" name="duallistbox_atividades[]">
                <!-- O IF tem que ficar DENTRO da tag OPTION -->
                {% for atividade in atividades %}
                <option value="{{ atividade.idatividade }}" 
                {% for latividade in licenca.atividade_id %}
                    {% if latividade==atividade.idatividade %}
                    selected="selected"
                    {% endif %}
                {% endfor %}>{{ atividade.descricao }}</option>
                {% endfor %}
            </select>
            <br>
            <hr>
            <h1><p class="text-center">Produtos</p></h1>
            <select multiple id="multiple" size="7" name="duallistbox_produtos[]">
                {% for produto in produtos %}
                <option value="{{ produto.idproduto }}"
                {% for lproduto in licenca.produto_id %}
                    {% if lproduto==produto.idproduto %}
                    selected="selected"
                    {% endif %}
                {% endfor %}>{{ produto.descricao }}</option>
                {% endfor %}
            </select>
            <br>
            <div class="form-row justify-content-between ml-3 mb-2">
                <button class="btn btn-primary" type="submit">Adicionar Atividades/Produtos</button>
                <div class="col-md-2">
                    <a href="{{ url_for('licenca_page.listarlicencas', id=empresa.idempresa) }}" class="btn btn-secondary">Cancelar/Voltar</a>
                </div>    
            </div>
        </form>
        <script src="/static/js/lista_dupla.js"></script>
    </div>
</body>
</html>